### ISSUE TITLE
The app requires the OAUTH_ env vars to be set on build time.

### ISSUE THREAD

**Issue by jakicoll** [pkoerner/expert-parakeet#95]
Currently, the Dockerfile solves this by mocking them so some random values.
Running `make uber` will also tell you to set them if they are not set.

**Comment by jakicoll** [comment]
BTW: This might even be a "security issue", since the build-time values of these might be included in the build output.

I'm not sure about this, but if they are, you would provide these secrets to everyone you give your build.

**Comment by JanKneiphof** [comment]
There is a \*compile-files\* flag in clojure, which is true during compilation and false otherwise
[https://clojuredocs.org/clojure.core/\*compile-files\*](https://clojuredocs.org/clojure.core/*compile-files*)
We could use this so that the expressions in `auth.clj` are simply not evaluated during compilation. 
What do you think?

**Comment by jakicoll** [comment]
Sound good. My first solution was to wrap the `define`s inside a (when-not \*compile-files*), but that broke the AOT compilation:
`Execution error (AssertionError) at ring.middleware.oauth2/wrap-oauth2 (oauth2.clj:120).
Assert failed: (every? valid-profile? (vals profiles))`

So the solution I'll provide as PR is to set them to an empty string on build time. -> The build finishes and you get a helpful AssertionError on runtime if you forgot to provide the environment variables.
